appnamespace: infrastructure
egressNetworksToBlock:
  - 10.0.0.0/20
  - 10.0.16.0/20
tennants:
- test-from-helm-multitenant-repo:
    source_repositories:
      - "https://github.com/KvalitetsIT/kithosting-LoginServices.git"
    allowInternetAccess : true
    denyAllNetwork: true
    limits:
      cpu: 1000
      memory: 200Gi
      longhorn.storageclass.storage.k8s.io/requests.storage: 100Gi
    default:
      limits:
        cpu: 10m
        memory: 128Mi
      request:
        cpu: 5m
        memory: 64Mi
    ingressAllowedNamespaces:
      - DataStorageServices
      - ingress-nginx
    egressAllowedNamespaces:
      - ingress-nginx

sharedServices:
- data-storage-services:
    repository: "https://github.com/KvalitetsIT/kithosting-LoginServices.git"
- login-services:
    repository: "https://github.com/KvalitetsIT/kithosting-LoginServices.git"

networkTest:
  image: kvalitetsit/kithosting-networkpolicytests
  tag: "0.0.1"