egressNetworksToBlock:
  - 10.0.0.0/20
  - 10.0.16.0/20
tennants:
- test-from-helm-multitenant-repo:
    limits:
      cpu: 1000
      memory: 200Gi
      longhorn.storageclass.storage.k8s.io/requests.storage: 100Gi
    allowInternetAccess : true
    ingressAllowedNamespaces:
      - DataStorageServices
      - ingress-nginx
    egressAllowedNamespaces:
      - ingress-nginx

sharedServices:
  - data-storage-services
  - login-services
