appnamespace: infrastructure
grafanaNamespace: infrastructure
infrastructure:
  blockIngress: true
  namespace: infrastructure
egressNetworksToBlock:
  - 10.0.0.0/20
  - 10.0.16.0/20
masterIp:
  - 192.168.0.6
  - 192.168.0.7
  - 192.168.0.8
tennants:
- test-from-helm-multitenant-repo:
    namespaceLabels: |
      test: true
      trivy-scan: true
    source_repositories:
      - "https://github.com/KvalitetsIT/kithosting-LoginServices.git"
    denyAllNetwork: false
    ingressAllowedGrafana: true
    dockerconfig:
      all-icr-io:
        annotations:
          hej: 123
        json: AgC14spw
    limits:
      cpu: 1000
      memory: 200Gi
      longhorn.storageclass.storage.k8s.io/requests.storage: 100Gi
    default:
      request:
        cpu: 5m
        memory: 64Mi
    ingressAllowedNamespaces:
      - DataStorageServices
      - ingress-nginx
    egressAllowedNamespaces:
      - ingress-nginx
    appOfApps:
      repository: "https://github.com/KvalitetsIT/kithosting-LoginServices.git"
      path: "/apps"
      targetRevision: "test"
      valueFiles:
        - "values.yaml"
        - "values-test.yaml"

- test2-from-helm-multitenant-repo:
    namespace: test-from-helm-multitenant-repo
    source_repositories:
      - "https://github.com/KvalitetsIT/kithosting-LoginServices.git"
    denyAllNetwork: false
    ingressAllowedGrafana: true
    dockerconfig:
      all-icr-io:
        annotations:
          hej: 123
        json: AgC14spw
    limits:
      cpu: 1000
      memory: 200Gi
      longhorn.storageclass.storage.k8s.io/requests.storage: 100Gi
    default:
      request:
        cpu: 5m
        memory: 64Mi
    ingressAllowedNamespaces:
      - DataStorageServices
      - ingress-nginx
    egressAllowedNamespaces:
      - ingress-nginx


sharedServices:
- data-storage-services:
    repository: "https://github.com/KvalitetsIT/kithosting-LoginServices.git"
    appOfApps:
      path: "/apps"
      targetRevision: "test"
      valueFiles:
        - "values.yaml"
        - "values-test.yaml"

- login-services:
    repository: "https://github.com/KvalitetsIT/kithosting-LoginServices.git"

networkTest:
  enabled: true
  image: kvalitetsit/kithosting-networkpolicytests
  tag: "0.0.1"