{{- range .Values.tennants }}
{{- range $name, $values := . }}

{{- if ($values.dockerconfigjson) }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $values.dockerconfigjsonName | default "pullSecret" }}
  namespace: {{ $name }}
spec:
  encryptedData:
    .dockerconfigjson: {{ $values.dockerconfigjson  }}
  template:
    metadata:
      name: {{ $values.dockerhubProxySecret | default "dockerhubProxy" }}
      namespace: {{ $name }}
    type: kubernetes.io/dockerconfigjson
---
{{ end }}
{{ end }}
{{ end }}