{{- range .Values.tennants }}
{{- range $name, $values := . }}

{{- if ($values.dockerconfig) }}
{{- range $id, $val := $values.dockerconfig}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $id }}
  namespace: {{ $name }}
  {{- if ($val.annotations) }}
  annotations:
    {{- with $val.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  encryptedData:
    .dockerconfigjson: {{ $val.json  }}
  template:
    metadata:
      name: {{ $id }}
      namespace: {{ $name }}
    type: kubernetes.io/dockerconfigjson
---

{{- if ($val.addToExtraDestinations) }}
{{- range $namespace, $destination := $values.extraDestinations}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $id }}
  namespace: {{ $namespace }}
  {{- if ($val.annotations) }}
  annotations:
    {{- with $val.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  encryptedData:
    .dockerconfigjson: {{ $val.json  }}
  template:
    metadata:
      name: {{ $id }}
      namespace: {{ $namespace }}
    type: kubernetes.io/dockerconfigjson
---
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}

{{- $valuesAtStart := .Values}}

{{- range .Values.sharedServices }}
{{- range $name, $values := . }}

{{- if ($values.dockerconfig) }}
{{- range $id, $val := $values.dockerconfig}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $id }}
  namespace: {{ $name }}
  {{- if ($val.annotations) }}
  annotations:
    {{- with $val.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  encryptedData:
    .dockerconfigjson: {{ $val.json  }}
  template:
    metadata:
      name: {{ $id }}
      namespace: {{ $name }}
    type: kubernetes.io/dockerconfigjson


---
{{ end }}
{{ end }}
{{ end }}
{{ end }}
