{{- range .Values.tenants }}
{{- range $name, $values := . }}
{{- if not ($values.namespace) }}
{{- if ($values.limits) }}
apiVersion: v1
kind: LimitRange
metadata:
  namespace: {{ $name }}
  name: {{$name}}-limit-range
  labels:
    type: tenant
spec:
  limits:
  - defaultRequest:
      {{- if ($values.default) }}
      cpu: {{ $values.default.request.cpu }}
      memory: {{ $values.default.request.memory }}
      {{- else }}
      cpu: 50m
      memory: 64Mi
      {{- end }}
    type: Container
---
{{ end }}
{{ end }}
{{ end }}
{{ end }}
