{{- range .Values.tennants }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .ns }}
---

apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: {{ .ns }}
  name: {{.ns}}-quota
spec:
  hard:
    cpu: {{ .limits.cpu }}
    memory: {{ .limits.memory  }}
    pods: {{ .limits.pods }}
    gold.storageclass.storage.k8s.io/requests.storage: {{ .limits.requests.storage }}

---
{{ end }}
