{{- range .Values.sharedServices }}
{{- range $name, $values := . }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    name: {{ $name }}
    type: shared-service

---
{{ end }}
{{ end }}

{{- range .Values.tenants }}
{{- range $name, $values := . }}
{{- if not ($values.namespace) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    name: {{ $name }}
    type: tenant
    {{- if ($values.namespaceLabels)}}
    {{- $values.namespaceLabels | nindent 4 }}
    {{- end }}

---
{{ end }}
{{ end }}
{{ end }}
