{{- range .Values.sharedServices }}
{{- range $name, $values := . }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    name: {{ $name }}
    type: shared-service

---
{{ end }}
{{ end }}

{{- range .Values.tennants }}
{{- range $name, $values := . }}

#=================== Namespace ===================
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    name: {{ $name }}
    type: tenant

---
{{ end }}
{{ end }}
