{{- if .Values.infrastructure.blockIngress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: infrastructure-block-ingress
  namespace: {{ .Values.infrastructure.namespace }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.infrastructure.namespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}