{{- $valuesAtStart := .Values}}

{{- range .Values.tennants }}
{{- range $name, $values := . }}

#Comments are from : https://www.openshift.com/blog/guide-to-kubernetes-ingress-network-policies

#=================== Network policies ===================
#The effect of the following policy specification is to isolate all pods, which means that only connections explicitly listed by other network policies will be allowed.

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}-default-deny-all
  namespace: {{ $name }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}-allow-dns-access
  namespace: {{ $name }}
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  podSelector: {}
  policyTypes:
  - Egress

---
#You can use the following network policy to allow all pod-to-pod communication within a namespace:
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}-allow-namespaces
  namespace: {{ $name }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ $name }}
{{- range $allowedIngress := $values.ingressAllowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ $allowedIngress }}
{{- end }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ $name }}
{{- range $allowedEngress := $values.egressAllowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ $allowedEngress }}
{{ end }}

{{- if ($values.allowInternetAccess)}}
{{- if $values.allowInternetAccess}}
    - ipBlock:
        cidr: 0.0.0.0/0
{{- if($valuesAtStart.egressNetworksToBlock) }}
        except: {{ $valuesAtStart.egressNetworksToBlock  }}
{{- end }}
{{- end }}
{{- end }}
---
{{ end }}
{{ end }}
