{{- $valuesAtStart := .Values}}

{{- range .Values.tennants }}
{{- range $name, $values := . }}

#Comments are from : https://www.openshift.com/blog/guide-to-kubernetes-ingress-network-policies

#=================== Network policies ===================
#You can use the following network policy to allow all pod-to-pod communication within a namespace:
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}-allow-namespaces
  namespace: {{ $name }}
  labels:
    type: tenant
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{- if and (not ($values.denyAllNetwork)) (not $values.denyAllNetwork) }}
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/20
    - namespaceSelector:
        matchLabels:
          name: {{ $name }}
{{- range $allowedIngress := $values.ingressAllowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ $allowedIngress }}
{{- end }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ $name }}
{{- range $allowedEngress := $values.egressAllowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ $allowedEngress }}
{{ end }}

{{- if ($values.allowInternetAccess)}}
{{- if $values.allowInternetAccess}}
    - ipBlock:
        cidr: 0.0.0.0/0
{{- if($valuesAtStart.egressNetworksToBlock) }}
        except:
          {{- range $toBlock := $valuesAtStart.egressNetworksToBlock }}
          - {{ $toBlock  }}
          {{- end}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
---
{{ end }}
{{ end }}
