{{- $valuesAtStart := .Values}}

{{- range .Values.tennants }}
{{- range $name, $values := . }}

#Comments are from : https://www.openshift.com/blog/guide-to-kubernetes-ingress-network-policies

#=================== Network policies ===================
#You can use the following network policy to allow all pod-to-pod communication within a namespace:
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}-allow-namespaces
  namespace: {{ $name }}
  labels:
    type: tenant
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{- if and (not ($values.denyAllNetwork)) (not $values.denyAllNetwork) }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ $name }}
{{- range $allowedIngress := $values.ingressAllowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ $allowedIngress }}
{{- end }}
{{- if $values.ingressAllowedGrafana }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ $.Values.grafanaNamespace }}
    ports:
      - protocol: TCP
        port: 9090 # Prometheus
      - protocol: TCP
        port: 3100 # Loki
{{- end }}
  egress:
  - to: # nodeLocal DNS
      - ipBlock:
          cidr: 169.254.20.10/32
    ports:
      - port: 53
        protocol: UDP
  - to: # Kube-api
      - ipBlock:
        cidr: 10.10.16.1/32
    ports:
      - port: 443
        protocol: TCP
  - to:
      - ipBlock: # Master01
        cidr: 192.168.0.6/32
      - ipBlock: # Master02
        cidr: 192.168.0.7/32
      - ipBlock: # Master03
        cidr: 192.168.0.8/32
    ports:
      - port: 6443
        protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ $name }}
{{- range $allowedEngress := $values.egressAllowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ $allowedEngress }}
{{ end }}

{{- end }}
---
{{ end }}
{{ end }}
