{{- $numberOfTenants := len .Values.tennants}}
{{- range .Values.tennants }}
{{- range $name, $values := . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{$name}}-networktests
  namespace: {{$name}}
spec:
  parallelism: 1
  template:
    metadata:
      name: {{$name}}-networktests
    spec:
      containers:
      - name: {{$name}}-networktests
        image: postman/newman:alpine
        command: ["run"]
        args: ["/etc/newman/test.postman_collection.json","--reporters","cli","--reporter-cli-no-failures"]
      restartPolicy: Never
---
{{ end }}
{{ end }}
