{{- $valuesAtStart := .Values}}

{{- range .Values.tennants }}
{{- range $name, $values := . }}
{{- if not ($values.namespace) }}

#Comments are from : https://www.openshift.com/blog/guide-to-kubernetes-ingress-network-policies

#=================== Network policies ===================
#You can use the following network policy to allow all pod-to-pod communication within a namespace:
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}-allow-namespaces
  namespace: {{ $name }}
  labels:
    type: tenant
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{- if and (not ($values.denyAllNetwork)) (not $values.denyAllNetwork) }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $name }}
{{- range $allowedIngress := $values.ingressAllowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $allowedIngress }}
{{- end }}
{{- if $values.ingressAllowedGrafana }}
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $.Values.grafanaNamespace }}
    ports:
      - protocol: TCP
        port: 9090 # Prometheus
      - protocol: TCP
        port: 3100 # Loki
{{- end }}
  egress:
  - to: # nodeLocal DNS
      - ipBlock:
          cidr: 169.254.20.10/32
      - ipBlock:
          cidr: 10.43.0.10/32
    ports:
      - port: 53
        protocol: UDP
  - to: # Kube-api
      - ipBlock:
          cidr: 10.10.16.1/32
    ports:
      - port: 443
        protocol: TCP
  - to: # Master
      {{- range $master := $valuesAtStart.masterIp }}
      - ipBlock:
          cidr: {{ $master }}/32
      {{- end }}
    ports:
      - port: 6443
        protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $name }}
{{- range $allowedEngress := $values.egressAllowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $allowedEngress }}
{{ end }}

{{- if and ($values.allowInternetAccess) $values.allowInternetAccess }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}-allow-internet
  namespace: {{ $name }}
  labels:
    type: tenant
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except: # Local and container net
              {{- range $toBlock := $valuesAtStart.egressNetworksToBlock }}
              - {{ $toBlock }}
              {{- end }}

{{- end }}

{{- end }}
---
{{ end }}
{{ end }}
{{ end }}
