{{- $numberOfTenants := len .Values.tennants}}
{{- range .Values.tennants }}
{{- range $name, $values := . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{$name}}-networktests
  namespace: {{$name}}
spec:
  parallelism: 1
  template:
    metadata:
      name: {{$name}}-networktests
    spec:
      containers:
      - name: {{$name}}-networktests
        image: dockerregistry.t0.hosting.kitkube.dk/dockerhub-proxy/kvalitetsit/kithosting-networkpolicytests
      restartPolicy: Never
---
{{ end }}
{{ end }}
