{{- if .Values.networkTest.enabled }}
{{- $numberOfTenants := len .Values.tennants}}
{{- range .Values.tennants }}
{{- range $name, $values := . }}
{{- if not ($values.namespace) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{$name}}-networktests
  namespace: {{$name}}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{$name}}-networktests
              image: {{$.Values.networkTest.image}}:{{$.Values.networkTest.tag}}
          restartPolicy: Never
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
