{{- $numberOfTenants := len .Values.tennants}}
{{- range .Values.tennants }}
{{- range $name, $values := . }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{$name}}-networktests
  namespace: {{$name}}
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{$name}}-networktests
              image: dockerregistry.t0.hosting.kitkube.dk/dockerhub-proxy/kvalitetsit/kithosting-networkpolicytests
          restartPolicy: Never
---
{{ end }}
{{ end }}
