{{- range .Values.tennants }}
{{- range $name, $values := . }}
{{- if ($values.limits) }}
#=================== Ressource quota ===================
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: {{ $name }}
  name: {{$name}}-quota
  labels:
    type: tenant
spec:
  hard:
{{- range $key,$val := $values.limits }}
    {{ $key }} : {{ $val }}{{ end }}
---
{{ end }}
{{ end }}
{{ end }}
