{{- $valuesAtStart := .Values}}

{{- range .Values.tennants }}
{{- range $name, $values := . }}
{{- if not $values.skipAppProject }}
#=================== Namespace ===================
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{$name}}
  namespace: {{$valuesAtStart.appnamespace}}
  labels:
    type: tenant-project
spec:
  # Project description
  description: Project containing applications for {{$name}}

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  {{- range $values.source_repositories }}
    - '{{.}}'
  {{ end }}

  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to {{$name}}
    policies:
    - p, proj:{{$name}}:read-only, applications, get, {{$name}}/*, allow
    - p, proj:{{$name}}:read-only, logs, get, {{$name}}/*, allow
    groups:
    - project-{{$name}}-readonly
  - name: sync
    description: Sync privileges to {{$name}}
    policies:
    - p, proj:{{$name}}:sync, applications, sync, {{$name}}/*, allow
    groups:
    - project-{{$name}}-sync
  - name: admin
    description: Admin privileges to {{$name}}
    policies:
    - p, proj:{{$name}}:admin, applications, *, {{$name}}/*, allow
    - p, proj:{{$name}}:admin, pods, *, {{$name}}/*, allow
    - p, proj:{{$name}}:admin, exec, *, {{$name}}/*, allow
    groups:
    - project-{{$name}}-admin
  
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: {{ $values.namespace | default $name}}
    server: https://kubernetes.default.svc
  - namespace: {{$valuesAtStart.appnamespace}}
    server: https://kubernetes.default.svc
  {{- range $name, $values :=  $values.extraDestinations }}
  - namespace: {{ $name }}
    {{- if ($values.server) }}
    server: {{ $values.server | default "https://kubernetes.default.svc" }}
    {{- else }}
    server: https://kubernetes.default.svc
    {{- end }}
  {{- end }}

  {{- if ($values.allowClusterResource ) }}
  {{- if $values.allowClusterResource }}
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  {{- end }}
  {{- end }}

---
{{- end }}
{{- end }}
{{- end }}
