{{- $valuesAtStart := .Values }}

{{- range .Values.tenants }}
{{- range $name, $values := . }}
{{- if not $values.skipAppProject }}
{{- if $values.appOfApps }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{$name}}-applications
  namespace: {{$valuesAtStart.namespaceArgo}}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ $values.appOfApps.repository }}
  type: git
type: Opaque
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
