{{- $valuesAtStart := .Values}}

{{- range .Values.tenants }}
{{- range $name, $values := . }}
{{- if not $values.skipAppProject }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{$name}}
  namespace: {{$valuesAtStart.namespaceArgo}}
  labels:
    type: tenant-project
spec:
  # Project description
  description: Project containing applications for {{$name}}

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  {{- range $values.source_repositories }}
    - '{{.}}'
  {{ end }}

  {{- if not $valuesAtStart.appsInArgoNamespace }}
   # Allow Applications from the tenants namespace
  sourceNamespaces:
  - {{ $values.namespace | default $name }}
  {{- end }}

  # Cluster and namespaces where applications are permitted to be deployed to
  destinations:
  - namespace: {{ $values.namespace | default $name}}
    server: https://kubernetes.default.svc
  {{- range $name, $values :=  $values.extraDestinations }}
  - namespace: {{ $name }}
    {{- if ($values.server) }}
    server: {{ $values.server | default "https://kubernetes.default.svc" }}
    {{- else }}
    server: https://kubernetes.default.svc
    {{- end }}
  {{- end }}

  {{- if ($values.allowClusterResource ) }}
  {{- if $values.allowClusterResource }}
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  {{- end }}
  {{- end }}

---
{{- end }}
{{- end }}
{{- end }}
