{{- $valuesAtStart := .Values}}

{{- range .Values.tennants }}
{{- range $name, $values := . }}
{{- if not $values.skipAppProject }}
{{- if $values.appOfApps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/instance: {{$name}}-applications
  name: {{$name}}-applications
  namespace: {{$valuesAtStart.appnamespace}}
spec:
  destination:
    namespace: {{$name}}
    server: https://kubernetes.default.svc
  project: {{$name}}
  source:
  {{- if $values.appOfApps.valueFiles }}
    helm:
      valueFiles:
    {{- range $name := $values.appOfApps.valueFiles }}
      - {{ $name }}
    {{- end }}
  {{- end }}
    path: {{$values.appOfApps.path}}
    repoURL: {{$values.appOfApps.repository}}
    targetRevision: {{$values.appOfApps.targetRevision}}
---
{{ end }}
{{ end }}
{{ end }}
{{ end }}