{{- $valuesAtStart := .Values}}

{{- range .Values.tennants }}
{{- range $name, $values := . }}
{{- if not $values.skipAppProject }}
{{- if $values.appOfApps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/instance: {{ $values.appOfApps.name | default (printf "%s-applications" $name) }}
  name: {{ $values.appOfApps.name | default (printf "%s-applications" $name) }}
  namespace: {{$valuesAtStart.appnamespace}}
spec:
  destination:
    namespace: {{$name}}
    server: https://kubernetes.default.svc
  project: {{$name}}
  source:
  {{- if $values.appOfApps.valueFiles }}
    helm:
      valueFiles:
    {{- range $name := $values.appOfApps.valueFiles }}
      - {{ $name }}
    {{- end }}
  {{- end }}
    path: {{$values.appOfApps.path}}
    repoURL: {{$values.appOfApps.repository}}
    targetRevision: {{$values.appOfApps.targetRevision}}
  {{- if  ($values.appOfApps.sync) }}
  syncPolicy:
  {{- if ($values.appOfApps.sync.auto)}}
    automated: 
      prune: {{ $values.appOfApps.sync.prune | default true}}
      selfHeal: {{ $values.appOfApps.sync.selfHeal | default true}}
  {{- end}}
  {{- end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{$name}}-applications
  namespace: {{$valuesAtStart.appnamespace}}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{$values.appOfApps.repository}}
  type: git
type: Opaque
---
{{ end }}
{{ end }}
{{ end }}
{{- end}}